/* Structured cross-platform reproducibility and full-label containment, twice. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{chromium,launchOptions}=require('./browser.cjs');
const root=path.resolve(__dirname,'../..'),base=process.env.ATLAS_PREVIEW||'http://127.0.0.1:8807/myatlas/knowledge-map/';
const expected={global:'1306993ec8a1b7a80edda4f620fb96ba5d4803c0d81ded334b92efa85cdf1174',personal:'a60fc22e272079c91f39cfed9c01af5865bae29120e6d6f7801b02da96cd6348',course8:'ab8e05971ca8fb9d077b491a766554f5b84118e068433afe4c17faa7e91fb89b',project113:'33dc51873bcbd33fa6ad2de854dd719e525706bdb764a50578570d1f73e89034',stage617:'24edf473c9e97b7ccbb287464302a4bbf6ffadff33efdc265076b5ae6b51455e'};
(async()=>{const browser=await chromium.launch(launchOptions);try{const result={browser:browser.version(),runs:[]};for(let run=0;run<2;run++){
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),rows={},errors=[];page.on('pageerror',e=>errors.push(e.message));
 for(const [name,query] of [['global',''],['personal','?view=skill-tree'],['course8','?course=8'],['project113','?project=113'],['stage617','?project=113&stage=617']]){
  await page.goto(base+query);await page.waitForFunction(()=>window.AtlasShell&&document.querySelector('#loading').hidden&&AtlasShell.state().activeFrame?.contentWindow.PublicProgress);
  rows[name]=await page.evaluate(()=>{const w=AtlasShell.state().activeFrame.contentWindow,s=(w.ScopeApp||w.AtlasV6).state(),L=s.L,overflow=[],labels=[];let fitted=0;
   if(s.renderer){for(const n of L.nodes){const entity=s.renderer.byKey.get(n.key),painted=entity.labels.filter(c=>c.style.endsWith('Label'));if(JSON.stringify(painted.map(c=>c.text))!==JSON.stringify(n.lines))overflow.push(n.key+':missing label');for(const c of painted){if(c.maxWidth!==n.width-44)overflow.push(n.key+':unbounded canvas label');labels.push(c.text);}}}
   else for(const group of w.document.querySelectorAll('g.node[data-key]')){const n=L.byKey.get(group.dataset.key);const elements=[...group.querySelectorAll('text.label tspan, text.label:not(:has(tspan))')];if(JSON.stringify(elements.map(e=>e.textContent))!==JSON.stringify(n.lines))overflow.push(n.key+':missing label');for(const e of elements){if(e.getComputedTextLength()>n.width-44+1/64)overflow.push(n.key+':horizontal overflow');const box=e.getBBox();if(box.y<0||box.y+box.height>n.height+0.01)overflow.push(n.key+':vertical overflow');if(e.hasAttribute('textLength'))fitted++;labels.push(e.textContent);}}
   return{geometry:[L.nodes.map(n=>[n.key,n.x,n.y,n.width,n.height,n.lines]),L.connectorSegments,L.trays,L.checkpoint],overflow,fitted,labels:labels.length,environment:{platform:w.navigator.platform,ua:w.navigator.userAgent,dpr:w.devicePixelRatio,viewport:[w.innerWidth,w.innerHeight]},source:w.PublicProgress.source.commit,learnedIds:w.PublicProgress.effective_learned_topic_ids};});
  const row=rows[name];row.hash=crypto.createHash('sha256').update(JSON.stringify(row.geometry)).digest('hex');if(name!=='personal'||JSON.stringify(row.learnedIds)===JSON.stringify(require('./validated-baseline.cjs').projection.effective_learned_topic_ids))assert.equal(row.hash,expected[name],name);assert.deepEqual(row.overflow,[],name);if(run)assert.deepEqual(row.geometry,result.runs[0][name].geometry,name+' repeat');
 }
 await context.route('**/knowledge-map/progress.json',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(require('./validated-baseline.cjs').projection)}));await page.goto(base+'?view=skill-tree');await page.waitForFunction(()=>window.AtlasShell&&document.querySelector('#loading').hidden&&AtlasShell.state().activeFrame?.contentWindow.AtlasV6?.state().L);const frozen=await page.evaluate(()=>{const L=AtlasShell.state().activeFrame.contentWindow.AtlasV6.state().L;return[L.nodes.map(n=>[n.key,n.x,n.y,n.width,n.height,n.lines]),L.connectorSegments,L.trays,L.checkpoint];});assert.equal(crypto.createHash('sha256').update(JSON.stringify(frozen)).digest('hex'),expected.personal);rows.frozenPersonal={hash:expected.personal,geometry:frozen,overflow:[],fitted:0,labels:0};assert.deepEqual(errors,[]);result.runs.push(rows);await context.close();}
 const out=process.env.ATLAS_GEOMETRY_ARTIFACT||path.join(root,'test-results/v66-geometry.json');fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(result)+'\n');console.log(JSON.stringify({status:'PASS',browser:result.browser,runs:result.runs.map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>[k,{hash:v.hash,fitted:v.fitted,labels:v.labels,overflow:v.overflow.length}])))}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
