const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'../..'),site=process.env.ATLAS_SITE||path.join(root,'build/pages/knowledge-map'),{chromium,launchOptions}=require('./browser.cjs');
const base=process.env.ATLAS_PREVIEW||'http://127.0.0.1:8807/myatlas/knowledge-map/';
const expected={global:'1306993ec8a1b7a80edda4f620fb96ba5d4803c0d81ded334b92efa85cdf1174',personal:'a60fc22e272079c91f39cfed9c01af5865bae29120e6d6f7801b02da96cd6348',course8:'ab8e05971ca8fb9d077b491a766554f5b84118e068433afe4c17faa7e91fb89b',project113:'33dc51873bcbd33fa6ad2de854dd719e525706bdb764a50578570d1f73e89034',stage617:'24edf473c9e97b7ccbb287464302a4bbf6ffadff33efdc265076b5ae6b51455e'};
const expectedProgress=JSON.parse(fs.readFileSync(path.join(site,'progress.json'))),expectedCourse=expectedProgress.course_project_completion.find(c=>c.course_id===8);
const checks=[],fingerprints={},errors=[],bad=[],requests=[],external=[];
const hash=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
function filesBelow(folder,prefix=''){return fs.readdirSync(folder,{withFileTypes:true}).flatMap(entry=>{const name=prefix+entry.name;if(entry.isDirectory())return filesBelow(path.join(folder,entry.name),name+'/');assert(entry.isFile());return[name];});}
(async()=>{const browser=await chromium.launch(launchOptions);try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin!==new URL(base).origin){external.push(u.href);return route.abort();}return route.continue();});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')console.error('Browser console:',m.text());});page.on('response',r=>{requests.push(new URL(r.url()).pathname);if(r.status()>=400)bad.push([r.url(),r.status()]);});
 const ready=()=>page.waitForFunction(()=>window.AtlasShell&&document.querySelector('#loading').hidden&&AtlasShell.state().activeFrame?.contentWindow.PublicProgress);
 const go=async(query='')=>{await page.goto(base+query);try{await ready();}catch(e){console.error({query,errors,bad,loading:await page.locator('#loading').innerText(),frames:await page.evaluate(()=>[...document.querySelectorAll('iframe')].map(f=>({src:f.src,error:f.contentDocument?.querySelector('#error')?.textContent,api:!!f.contentWindow.AtlasV6,progress:!!f.contentWindow.PublicProgress})))});throw e;}};
 const state=()=>page.evaluate(()=>{const w=AtlasShell.state().activeFrame.contentWindow,s=(w.ScopeApp||w.AtlasV6).state();return{route:AtlasShell.state().route,counts:{categories:s.m?.raw?.categories?.length,topics:s.m?.raw?.topics?.length},progress:w.PublicProgress.global,completed:w.PublicProgress.completed_project_count,registry:s.m?.registry.size,inventory:{courses:AtlasShell.state().ux.courses.size,projects:AtlasShell.state().ux.projects.size,stages:AtlasShell.state().ux.stages.size}};});
 const geometry=()=>page.evaluate(()=>{const w=AtlasShell.state().activeFrame.contentWindow,L=(w.ScopeApp||w.AtlasV6).state().L;return[L.nodes.map(n=>[n.key,n.x,n.y,n.width,n.height,n.lines]),L.connectorSegments,L.trays,L.checkpoint];});
 await go();assert.deepEqual(await page.locator('#application-nav a').allTextContents(),['Atlas','My Skill Tree','LeetCode']);
 const initial=await state();assert.deepEqual(initial.counts,{categories:849,topics:3106});assert.deepEqual(initial.inventory,{courses:52,projects:391,stages:1967});assert.equal(initial.registry,3955);assert.equal(await page.evaluate(()=>AtlasShell.state().activeFrame.contentWindow.AtlasV6.state().m.raw.references.length),0);assert.equal(JSON.parse(fs.readFileSync(path.join(root,'src/myatlas/knowledge-atlas-scope-pyramid/scope-index.json'))).course_project_associations.courses.reduce((n,c)=>n+new Set(c.project_ids).size,0),867);assert.equal(initial.completed,expectedProgress.completed_project_count);assert.equal(initial.progress.learned,expectedProgress.global.learned);assert.equal(initial.progress.verified,expectedProgress.global.verified);
 fingerprints.global=hash(await geometry());assert.equal(fingerprints.global,expected.global);checks.push('Complete Global render and catalog/portfolio inventories; generated progress baseline');
 for(const [name,query,eligible] of [['course8','?course=8',89],['project113','?project=113',26],['stage617','?project=113&stage=617',12]]){
  await go(query);const s=await page.evaluate(()=>{const {ux,scope}=AtlasShell.state().activeFrame.contentWindow.ScopeApp.state();return ux.analytics.scope(scope.scope_type,scope.scope_id);});const type=name==='course8'?'courses':name==='project113'?'projects':'stages',id=name==='course8'?8:name==='project113'?113:617,expectedScope=expectedProgress.coverage[type].find(s=>s.id===id);assert.deepEqual([s.learned,s.eligible],[expectedScope.learned,eligible]);
  fingerprints[name]=hash(await geometry());assert.equal(fingerprints[name],expected[name]);
  const frame=page.frameLocator('iframe[data-active=true]');await frame.locator('#inspector-toggle').click();assert.match(await frame.locator('#inspector').innerText(),new RegExp(expectedScope.learned+' / '+eligible+' learned'));
  await page.reload();await ready();assert.equal(hash(await geometry()),expected[name]);
 }
 checks.push('Course 8, Project 113, Stage 617, Inspector, direct scoped reload and accepted fingerprints');
 await go('?view=skill-tree');await page.waitForFunction(()=>AtlasShell.state().activeFrame.contentWindow.SkillProgress);
 fingerprints.personal=hash(await geometry());if(JSON.stringify(expectedProgress.effective_learned_topic_ids)===JSON.stringify(require('./validated-baseline.cjs').projection.effective_learned_topic_ids))assert.equal(fingerprints.personal,expected.personal);const f=page.frameLocator('iframe[data-active=true]');const overview=await f.locator('#progress-overview').innerText();assert.match(overview,new RegExp(expectedProgress.global.verified+' verified'));assert.match(overview,new RegExp('Projects completed\\n'+expectedProgress.completed_project_count+'\\b'));assert.match(overview,new RegExp('Course Projects\\n'+expectedCourse.completed+' / 11 completed'));assert.doesNotMatch(overview,/Not recorded|catalog/);if(expectedProgress.portfolio.completed_course_count===null)assert.doesNotMatch(overview,/Courses completed/);else assert.match(overview,/Courses completed/);await f.locator('#progress-expand').click();assert.equal(await f.locator('#progress-panel details[data-progress-details]').getAttribute('open'),null);assert.match(await f.locator('#progress-panel').innerText(),/Introduction to Java/);assert.match(await f.locator('#progress-panel').innerText(),new RegExp(expectedCourse.completed+' / 11 associated projects completed'));assert.doesNotMatch(await f.locator('#progress-panel').innerText(),/Not recorded|evidenced learned|Denominator:/);await f.locator('#progress-panel details[data-progress-details] > summary').click();assert.match(await f.locator('#progress-panel').innerText(),/Official Hyperskill/);if(expectedProgress.completed_project_ids.includes(113))assert.match(await f.locator('#progress-panel').innerText(),/Owner-attested Project 113/);await f.locator('#progress-close').click();await page.frameLocator('iframe[data-active=true]').locator('#progress-overview').getByText(expectedProgress.global.learned+' / 3,106').waitFor();
 checks.push('Final compact My Skill Tree overview, exact unique Project and Course8 counts from projection, hidden missing Course completions, one collapsed Data details retaining provenance; accepted geometry');
 await go('?course=8');await page.evaluate(()=>AtlasShell.state().activeFrame.contentWindow.ScopeApp.select('topic:36'));await page.frameLocator('iframe[data-active=true]').locator('#global-link').click();await ready();await page.waitForFunction(()=>AtlasShell.state().route.key==='topic:36');assert.equal(await page.evaluate(()=>AtlasShell.state().activeFrame.contentWindow.AtlasV6.state().selected),'topic:36');
 await page.goBack();await ready();assert.equal((await state()).route.course,'8');await page.goForward();await ready();assert.equal((await state()).route.key,'topic:36');
 checks.push('Exact-ID Show in Global, shell Back/Forward and semantic route');
 for(const query of ['?scope=project&id=113','?scope=stage&id=617','?course_id=8']){await go(query);assert.equal((await state()).route.view,'atlas');assert((await state()).route.project||(await state()).route.course);}
 await go('global.html?key=topic%3A36');assert.equal((await state()).route.key,'topic:36');assert(page.url().startsWith(base+'index.html?'));
 await go('?view=my-atlas');assert.equal((await state()).route.view,'skill-tree');
 await go('#category:73');assert.equal((await state()).route.key,'category:73');
 await go('views/knowledge-atlas-v6-skill-tree/index.html');assert.equal((await state()).route.view,'skill-tree');
 checks.push('Legacy scope/id, *_id, Global exact-ID/hash and personal entry redirects without loops');
 await page.setViewportSize({width:390,height:844});await go('?project=113&stage=617');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.locator('#application-nav a').count(),3);await page.frameLocator('iframe[data-active=true]').locator('#inspector-toggle').click();assert(await page.frameLocator('iframe[data-active=true]').locator('#inspector').isVisible());
 await go('?view=skill-tree');const narrow=page.frameLocator('iframe[data-active=true]');await narrow.locator('#progress-expand').click();assert.equal(await narrow.locator('#progress-panel').evaluate(p=>p.scrollWidth<=p.clientWidth),true);assert.equal(await narrow.locator('#progress-overview').evaluate(e=>e.getBoundingClientRect().right<=e.ownerDocument.defaultView.innerWidth),true);assert(await narrow.locator('#progress-close').isVisible());await narrow.locator('#progress-close').click();checks.push('390px viewport, three tabs, Stage pyramid/Inspector and compact Skill Tree overview/scrolling panel');
 const response=await context.request.get(base+'progress.json');assert.equal(response.status(),200);assert.equal((await response.json()).completed_project_count,expectedProgress.completed_project_count);
 const {execFileSync}=require('node:child_process');const sync=()=>execFileSync('python3',process.env.HYPERSKILL_EVIDENCE_ROOT?['-B','scripts/sync-hyperskill-projects.py','--evidence-root',process.env.HYPERSKILL_EVIDENCE_ROOT]:['-B','scripts/sync-project-completion.py'],{cwd:root});const first=sync();assert(first.equals(sync()));const committedProjection=JSON.parse(first).projection;assert.deepEqual(committedProjection,JSON.parse(fs.readFileSync(path.join(site,'progress.json'))));assert.equal(committedProjection.portfolio.completed_course_count,expectedProgress.portfolio.completed_course_count);assert.deepEqual(committedProjection.completed_project_ids,expectedProgress.completed_project_ids);const manifest=JSON.parse(fs.readFileSync(path.join(site,'runtime-manifest.json')));const digest=b=>crypto.createHash('sha256').update(b).digest('hex');for(const row of manifest.source_assets)assert.equal(digest(execFileSync('git',['show','HEAD:'+row.source],{cwd:root,maxBuffer:64*1024*1024})),row.source_sha256);for(const [name,sha] of Object.entries(manifest.inventory))assert.equal(digest(fs.readFileSync(path.join(site,name))),sha);checks.push('Deterministic Git projection matches generated site; all packaged source assets match committed Git blobs; complete candidate manifest exact; historic integrity checked separately');
 const projection=JSON.parse(fs.readFileSync(path.join(site,'progress.json'))),catalog=JSON.parse(fs.readFileSync(path.join(root,'src/myatlas/knowledge-atlas-scope-pyramid/catalog.json'))),scopes=JSON.parse(fs.readFileSync(path.join(root,'src/myatlas/knowledge-atlas-scope-pyramid/scope-index.json')));
 const learned=new Set(projection.effective_learned_topic_ids),next=scopes.projects.filter(p=>p.state==='KNOWN'&&p.scope_id!==113&&p.explicit_topic_ids.some(id=>!learned.has(id))).sort((a,b)=>a.explicit_topic_ids.length-b.explicit_topic_ids.length||a.scope_id-b.scope_id)[0];
 const synthetic=require(path.join(root,'scripts/knowledge_atlas/completion_projection.cjs')).project({catalog,scopes,source:{validation_only:true},completion:{policy:projection.policy,projects:[...projection.projects,{project_id:next.scope_id,status:'completed',attested_by:'owner',observed_at:'2026-10-08T14:00:00Z',source:'validation-only/.hyperskill-import.json',requirements_state:'KNOWN',topic_ids:[...new Set(next.explicit_topic_ids)].sort((a,b)=>a-b)}]}});
 assert(synthetic.global.learned>expectedProgress.global.learned);assert.equal(synthetic.global.verified,expectedProgress.global.verified);
 await context.route('**/knowledge-map/progress.json',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(synthetic)}));await page.setViewportSize({width:1440,height:1000});
 await go();assert.equal((await state()).progress.learned,synthetic.global.learned);assert.equal(hash(await geometry()),expected.global);
 await go('?course=8');assert.equal(hash(await geometry()),expected.course8);await go('?view=skill-tree');await page.frameLocator('iframe[data-active=true]').locator('#progress-overview').getByText(synthetic.global.learned+' / 3,106').waitFor();
 assert.equal(await page.evaluate(()=>AtlasShell.state().activeFrame.contentWindow.AtlasV6.state().m.raw.counts.learned),synthetic.global.learned);
 checks.push('Synthetic newly completed existing Project updates Global/Scope/Skill Tree via JSON only; verification and Global/Scope geometry unchanged');
 assert.deepEqual(errors,[]);assert.deepEqual(bad,[]);assert.deepEqual(external,[]);assert(requests.every(p=>p.startsWith(new URL(base).pathname)));assert(requests.includes(new URL('progress.json',base).pathname));
 const result={status:'PASS',source_commit:manifest.source_commit,source_assets:manifest.source_assets.length,checks,fingerprints,baseline:initial,synthetic:{project_id:next.scope_id,learned:synthetic.global.learned,verified:synthetic.global.verified,newly_learned_topic_ids:synthetic.effective_learned_topic_ids.filter(id=>!learned.has(id))},requested_assets:[...new Set(requests)].sort(),errors,bad,external,preview:base};
 const artifact=process.env.ATLAS_REVIEW_ARTIFACT||path.join(root,'test-results/v66-release.json');fs.mkdirSync(path.dirname(artifact),{recursive:true});fs.writeFileSync(artifact,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:result.status,checks,synthetic:result.synthetic}));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
